version: "3.8"

services:
  prometheus:
    image: ubuntu/prometheus
    container_name: prometheus-krushna-jagdale
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: always


  grafana:
    image: grafana/grafana
    container_name: grafana-krushna
    ports:
      - "3000:3000"
    networks:
      - monitoring
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - "8082:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge

